/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppCollectionsRouteImport } from './routes/app.collections'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppLogRouteImport } from './routes/app.log'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as QIdRouteImport } from './routes/q.$id'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AppQuotesIdRouteImport } from './routes/app.quotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const QIdRoute = QIdRouteImport.update({
  id: '/q/$id',
  path: '/q/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppQuotesIdRoute = AppQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/connect': typeof AppConnectRoute
  '/app/log': typeof AppLogRoute
  '/app/settings': typeof AppSettingsRoute
  '/q/$id': typeof QIdRoute
  '/s/$slug': typeof SSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/quotes/$id': typeof AppQuotesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/connect': typeof AppConnectRoute
  '/app/log': typeof AppLogRoute
  '/app/settings': typeof AppSettingsRoute
  '/q/$id': typeof QIdRoute
  '/s/$slug': typeof SSlugRoute
  '/app': typeof AppIndexRoute
  '/app/quotes/$id': typeof AppQuotesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/signup': typeof SignupRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/collections': typeof AppCollectionsRoute
  '/app/connect': typeof AppConnectRoute
  '/app/log': typeof AppLogRoute
  '/app/settings': typeof AppSettingsRoute
  '/q/$id': typeof QIdRoute
  '/s/$slug': typeof SSlugRoute
  '/app/': typeof AppIndexRoute
  '/app/quotes/$id': typeof AppQuotesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/signup'
    | '/app/approvals'
    | '/app/catalog'
    | '/app/collections'
    | '/app/connect'
    | '/app/log'
    | '/app/settings'
    | '/q/$id'
    | '/s/$slug'
    | '/app/'
    | '/app/quotes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/signup'
    | '/app/approvals'
    | '/app/catalog'
    | '/app/collections'
    | '/app/connect'
    | '/app/log'
    | '/app/settings'
    | '/q/$id'
    | '/s/$slug'
    | '/app'
    | '/app/quotes/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/signup'
    | '/app/approvals'
    | '/app/catalog'
    | '/app/collections'
    | '/app/connect'
    | '/app/log'
    | '/app/settings'
    | '/q/$id'
    | '/s/$slug'
    | '/app/'
    | '/app/quotes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  SignupRoute: typeof SignupRoute
  QIdRoute: typeof QIdRoute
  SSlugRoute: typeof SSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collections': {
      id: '/app/collections'
      path: '/collections'
      fullPath: '/app/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log': {
      id: '/app/log'
      path: '/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/q/$id': {
      id: '/q/$id'
      path: '/q/$id'
      fullPath: '/q/$id'
      preLoaderRoute: typeof QIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/quotes/$id': {
      id: '/app/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/app/quotes/$id'
      preLoaderRoute: typeof AppQuotesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppConnectRoute: typeof AppConnectRoute
  AppLogRoute: typeof AppLogRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuotesIdRoute: typeof AppQuotesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCollectionsRoute: AppCollectionsRoute,
  AppConnectRoute: AppConnectRoute,
  AppLogRoute: AppLogRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuotesIdRoute: AppQuotesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  SignupRoute: SignupRoute,
  QIdRoute: QIdRoute,
  SSlugRoute: SSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
